spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/exampledb?useUnicode=true&serverTimezone=Asia/Seoul
    username: root
    password: root



